name: VoteNotify
main: de.exxe.VoteNotify.Main.Main
version: 1.7.1
author: exxe
permissions: 
    votenotify.admin:
depends: [Votifier]
commands:
    votenotify:
        aliases: [vn]
permissions:
    votenotify.admin:
        default: false